### ISSUE TITLE
develop schema for open data inventory

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-manual#10]
We need to decide what we want to know now/next/later about each item in the open data inventory. This will inform how we label the columns of the new inventory table.

**Comment by haileypate** [comment]
Background: The first round of the inventory activity (completed by departments last year) yielded inconsistent results. We need to get a clearer idea of what information assets each department is dealing with so we can design a program to improve our open data in a meaningful and responsible way. At a minimum, we  need to resolve discrepancies between the datasets published on Socrata and the items listed in the inventory. 

to be finished

**Comment by haileypate** [comment]
Current plan is to start with the [dataset schema](https://project-open-data.cio.gov/v1.1/schema/) built by Project Open Data. Next steps include:

- [ ] Schedule a time for liaisons & stakeholders to meet to review and give feedback on suggested items
 to be finished

**Comment by luqmaan** [comment]
That dataset schema looks great. :+1:

**Comment by haileypate** [comment]
need to bring the metadata content into the new version of the manual

**Comment by haileypate** [comment]
schema has been developed, required elements have been brought into the open data manual
