### ISSUE TITLE
plan for metadata standard review meeting

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-manual#13]

**Comment by haileypate** [comment]
@BradleyMcCarty Hi, any insight as to when this should take place?

**Comment by BradleyMcCarty** [comment]
I'll be introducing my team to GitHub today and this is one of the areas we'll be discussing. We'll begin by having them all create accounts

**Comment by haileypate** [comment]
we've been having lots of meetings and developed a [list of items](https://airtable.com/shrm28ld0rOZuzPQW) for the first draft of the metadata standard. closing this issue
