### ISSUE TITLE
making it easier for the public to contact a dataset steward

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-manual#29]
@cronins submitted this finding today: 

> Someone had a question about a dataset I had posted on the data portal. This seems to be a tangential issue to the workflow we’ve been discussing. My name is listed if you click about in the data, but you have to log in to get to see more information about me. I wonder if we could make it easier for folks to find the person who posted the data if they have questions.... Interesting as well that this query didn’t get forwarded to the open data liaisons at the library, which is me and Joe Faulk.

Also, Sarah is the "owner" of the dataset on Socrata. 

My response: 
> Sarah, 

> Thanks for this great feedback. I agree that restricting contact information behind a login seems like an unnecessary barrier. I see at least few different ways to address this: 
- ​Submit a feature request to Socrata, and/or: 
- Add contact information as part of the required metadata, and/or:
- For your datasets, add a link to the liaisons for your department as part of the metadata (for example, I maintain a current list of dept liaisons... when a link is clicked, we could have that list show up in a new tab, filtered to show the name/email of just the library liaisons)

So... some questions to discuss:  
- **Do we want to use the metadata standard to help users contact the stewards of a particular dataset?**
- **How else could we make it easier for users to submit dataset questions to the appropriate person?**
- @cityofaustin/suggestion-workflow-team, **Should this use case be addressed by the solution we are developing for dataset suggestions now/next/later?**

cc @BradleyMcCarty

**Comment by cronins** [comment]
As a librarian, I always like metadata standards. :-) I think that could be particularly helpful to use the metadata to make it a bit easier to find the dataset owner. I think the City can be complicated for the public, and it's not always easy to understand the various departments or who to contact. 

Thanks for opening a dialog about this. I think this is something that could be addressed after we finish the suggestion workflow.

Sarah

**Comment by haileypate** [comment]
we've added the contact name and email as part of the metadata standard =)

see https://github.com/cityofaustin/open-data-manual/issues/34. 

woot!
