### ISSUE TITLE
Data Request Page Comment Threads are Wonky

### ISSUE THREAD

**Issue by CodeMcConnell** [cityofaustin/open-data-manual#30]
Hailey suggested that I post this as an issue since it confused me this morning. On the extant request system on the data portal, the comments on requests are displayed reverse-chronologically. This confused me this morning when I received notification of a comment. I expected the new comment to appear at the bottom of the thread, so I thought it wasn't visible on the web. 

Most of the message boards I use display comments chronologically, so I think this breaks user expectations. It may be the case that I have very idiosyncratic taste in message boards and this is typical threading display.

**Comment by haileypate** [comment]
yeah.. unfortunately we don't have any control over this. i think this passed along to socrata, but i'll go follow up. hopefully, now that the we have a spec (aka wish list) for an open data suggestion feature, we'll be able to deliver a better user experience sooner rather than later ;)
