### ISSUE TITLE
"category" as a metadata element

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-manual#32]
from janette's team... 

important questions to address.. 

[ ] - how will we decide what the categories for datasets will be?
[ ] - who will be doing this?
[ ] - how might these categories align with how open performance works?
[ ] - what is the the relationship (if any) to the service areas in open performance?

**Comment by haileypate** [comment]
the category project in the Sprint 2.3 is tackling this. sent email to brad =)

**Comment by BradleyMcCarty** [comment]
Closed, Okay.  I'll integrate this into other information we're putting together.
