### ISSUE TITLE
Data Inventory and Application Portfolio Manager

### ISSUE THREAD

**Issue by wrays** [cityofaustin/open-data-manual#37]
I'm thinking there may be some value to considering the developing data inventory alongside the existing Application Portfolio Manager.

Here's a link to the Application Portfolio Manager: http://coaspweb1/sites/CTMOPAQA/opa/default.aspx

And a link to the Applications: http://coaspweb1/sites/CTMOPAQA/opa/Lists/Application%20Information/Application%20Support%20Group.aspx

Applications are not the only Data Source for Datasets, but they are primary and important.

I've been comparing the fields we have established so far for inventory which are viewable in Airtable: https://airtable.com/tbll3avqmLebbGmS9/viwxHAlM6pk5JrpX8 

And which are based off SF's example.

So some of the fields in the Application Portfolio Manager that could be relevant to the Data Inventory and/or are similar fields include:

- Application Name
- Application Type
- Product Name
- Data Classification
- Department (Owned by)
- Application Support Group
- Primary Application Support
- APM Data Quality Owner
- Go Live Date
- Date Retired

There may be others. I encourage people to look at all the fields for ideas.

Data Classification, for example, includes these check boxes:

- Available for Public consumption
- CJIS (Criminal Justice Information System)
- HIPAA (Health Insurance Portability and Accountability Act)
- PII (Personally Identifiable Information)
- PCI (Payment Card Industry)

These are standards already set up in the APM and they seem to be applicable to the Data Inventory. 

The San Francisco example which we've been modelling uses these terms:

- Data Steward (Business Knowledge)
- Data Custodian (Technical Knowledge)

I think Data Custodian is akin to the Primary Application Support
And Data Steward is akin to the APM Data Quality Owner

The Application Type field on APM refers to whether the Application is:

- Commercial Off-the-shelf
- Custom by Vendor
- Custom In House
- External System
- Open Source
- SAAS

So far in HHSD, I've run into applications that third party vendors (CTK), State of Texas DB applications, applications by Corporate COA, applications developed within HHSD, and others.

Each of these presents its own set of circumstances regarding who owns and controls the data and the ease or difficulty of getting access to datasets. Good information to track.

The SF model uses:

- Start Date
- End Date

The APM fields include:

- Go Live Date
- Date Retired
 
I'm thinking that there could be or may be some possible future interoperability between the Application Portfolio Manager and the Data Inventory.

It makes sense.

The APM is a database of the data sources.
The Data Inventory is a database of the datasets within the data sources.

These two systems should somehow be able to connect with each other.

So it makes sense to use common fields and since the APM is already established to borrow field names from it.

**Comment by haileypate** [comment]
@wrays -- reviewing these again.. they are such great notes! will close here and copy into our plans repo
